import { resolve } from "node:path";
import { expect, test } from "vitest";
import { generatedFiles, staleToolDocuments } from "../../scripts/render-docs.ts";
import { packageRoot } from "./runner.ts";

/**
 * The documentation, generated by the vitest run: every README and per-tool
 * page is a file snapshot rendered from the scenario definitions and
 * captured responses, so `vitest -u` writes docs the same way it writes
 * responses and a plain run fails on drift. Vitest flushes new snapshots at
 * test-file completion, so this lives in its own file; `pnpm run capture`
 * runs it after the capture file, in order. Editing a generated file
 * directly is not anyone's to do — change the source and re-run.
 */
test("documentation renders from the captures", { timeout: 60_000 }, async () => {
  const repositoryRoot = resolve(packageRoot, "../..");
  for (const { target, render } of await generatedFiles()) {
    await expect(await render()).toMatchFileSnapshot(resolve(repositoryRoot, target));
  }
  expect(await staleToolDocuments(), "pages for tools with no cases — remove them").toEqual([]);
});
